"""
Which inputs move the top ideas, and where they break.

Run:  python3 analysis/thresholds.py   -> writes analysis/thresholds.md
"""

from dataclasses import replace
from pathlib import Path

import model as M

TOP = ["gtmlists", "secq", "medchron"]
PARAMS = {  # name: (low multiplier, high multiplier)
    "pos_rate": (0.5, 1.5),
    "close_rate": (0.5, 1.5),
    "arpu": (0.8, 1.2),
    "churn": (0.5, 1.5),
    "delivery_h": (0.67, 1.5),
}


def idea(key):
    return next(i for i in M.IDEAS if i.key == key)


def run(i, s):
    return M.metrics(replace(i, scenarios={"base": s}), "base")


def solve(i, param, target_fn, lo, hi, iters=40):
    """Bisection on a parameter value so that target_fn(metrics) crosses 0."""
    base = i.scenarios["base"]
    f = lambda v: target_fn(run(i, replace(base, **{param: v})))
    flo, fhi = f(lo), f(hi)
    if flo * fhi > 0:
        return None
    for _ in range(iters):
        mid = (lo + hi) / 2
        fm = f(mid)
        if fm * flo > 0:
            lo, flo = mid, fm
        else:
            hi = mid
    return (lo + hi) / 2


def fmt(param, v):
    if v is None:
        return "not reached in range"
    if param in ("pos_rate", "close_rate", "churn"):
        return f"{v*100:.2f}%"
    if param == "arpu":
        return f"${v:,.0f}/mo"
    return f"{v:.2f} h"


def main():
    out = ["# Thresholds and tornado (base case, generated by analysis/thresholds.py)\n"]
    for key in TOP:
        i = idea(key)
        base = i.scenarios["base"]
        b = run(i, base)
        out.append(f"## {i.name}\n")
        out.append(f"Base: 12-mo true profit {M.money(b['true_profit'])}, month-12 run-rate {M.money(b['run12'])}/h, true BE {b['true_be']}\n")
        out.append("| Input | Base value | Low -> 12-mo true / m12 $/h | High -> 12-mo true / m12 $/h | Value where m12 run-rate = $101/h | Value where 36-mo true break-even disappears |")
        out.append("|---|---|---|---|---|---|")
        for p, (lo_m, hi_m) in PARAMS.items():
            v0 = getattr(base, p)
            lo = run(i, replace(base, **{p: v0 * lo_m}))
            hi = run(i, replace(base, **{p: v0 * hi_m}))
            rng = (v0 * 0.2, v0 * 5)
            t_run = solve(i, p, lambda m: m["run12"] - M.HOURLY, *rng)
            t_be = solve(i, p, lambda m: 0.5 - M.be_num(m["true_be"]) / 72, *rng)  # be_num 99 = none within 36
            out.append(f"| {p} | {fmt(p, v0)} | x{lo_m}: {M.money(lo['true_profit'])} / {M.money(lo['run12'])} | "
                       f"x{hi_m}: {M.money(hi['true_profit'])} / {M.money(hi['run12'])} | {fmt(p, t_run)} | {fmt(p, t_be)} |")
        out.append("")

    # What would have to be true for lower-ranked ideas to enter the top 3
    out.append("## What lifts the lower-ranked ideas\n")
    up = idea("upwork")
    for price, hrs in ((3500, 28), (4000, 24), (5000, 24)):
        m = run(up, replace(up.scenarios["base"], setup_fee=price, onboard_h=hrs))
        out.append(f"- Upwork at ${price:,}/project and {hrs} h: m12 run-rate {M.money(m['run12'])}/h, 12-mo true {M.money(m['true_profit'])}")
    mt = idea("meetings")
    for close in (0.30, 0.40):
        m = run(mt, replace(mt.scenarios["base"], close_rate=close))
        out.append(f"- Meetings agency with a {close:.0%} close rate: 12-mo true {M.money(m['true_profit'])}, m12 {M.money(m['run12'])}/h, true BE {m['true_be']}")
    mc = idea("medchron")
    s = mc.scenarios["base"]
    contractor = replace(s, delivery_h=s.delivery_h * 0.25, var_cash=s.var_cash + s.delivery_h * 0.75 * 35)
    m = run(mc, contractor)
    out.append(f"- Medical chronology with a $35/h QA contractor doing 75% of checking: 12-mo true {M.money(m['true_profit'])}, "
               f"m12 {M.money(m['run12'])}/h, true BE {m['true_be']}, capacity-capped: {'yes' if m['capped'] else 'no'}")
    old = M.HOURLY
    M.HOURLY = 50.0
    r = {k: {sc: M.metrics(i, sc) for sc in ('cons', 'base', 'opt')} for k, i in ((i.key, i) for i in M.IDEAS)}
    order, _ = M.overall(r)
    M.HOURLY = old
    out.append(f"- Time valued at $50/h instead of $101/h: overall order becomes {', '.join(order[:6])}")
    Path(__file__).with_name("thresholds.md").write_text("\n".join(out) + "\n")
    print("\n".join(out))


if __name__ == "__main__":
    main()
